### PR TITLE
ELEMENTS-885: fix nuxeo-selectivity multiple and single inputs height (Backport 10.10)

### PR DESCRIPTION
**Pull request by semisse**

### CODE REVIEW

**Comment by guirenard** [comment]
:+1:

**Comment by guirenard** [comment]
master's PR https://github.com/nuxeo/nuxeo-elements/pull/56

**Comment by Gabez0r** [comment]
Same comment as https://github.com/nuxeo/nuxeo-elements/pull/56#discussion_r270938426

**Comment by semisse** [comment]
Web-UI pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/23/

**Comment by nmpcunha** [comment]
👍

**Comment by Gabez0r** [comment]
👍

**Pull request merged**
