### PR TITLE
ELEMENTS-1299: fix nuxeo-path-suggestion validation (Backport 10.10)

### PR DESCRIPTION
**Pull request by richardsd**
Backport of https://github.com/nuxeo/nuxeo-elements/pull/329

### CODE REVIEW

**Comment by richardsd** [comment]
Note: not going to merge it until we have the pipeline running again.

**Review by mnixo — APPROVED** [review]

**Review by semisse — DISMISSED** [review]

**Comment by richardsd** [comment]
Pipeline running at https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/698 🕐

**Review by mnixo — DISMISSED** [review]

**Review by Gabez0r — DISMISSED** [review]

**Comment by richardsd** [comment]
There was a missing use case with the previous approach (maybe that happens in master too):
- if the `autoValidate` is true, then trying to update the `invalid` property of the typeahead element doesn't work.

This solution consists in creating a custom validator in Polymer global namespace that is passed to the typeahead element. Wdyt? Feedback is very welcome.

**Comment by richardsd** [comment]
path_suggestion_validator

**Review by mnixo — APPROVED** [review]

**Review by semisse — APPROVED** [review]

**Comment by richardsd** [comment]
Pipeline running at https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/706/ 🕐

**Review by semisse — APPROVED** [review]

**Review by Gabez0r — APPROVED** [review]

**Pull request merged**
