### PR TITLE
ELEMENTS-1504: remove nuxeo-tag content overlap - backport 10.10

### PR DESCRIPTION
**Pull request by swarnadipa-dev**

### CODE REVIEW

**Review by SnehalNaik-DEV — DISMISSED** [review]
Looks good.

**Review by rakeshkumar1019 — DISMISSED** [review]

**Review by Gabez0r — APPROVED** [review]

**Review by Gabez0r — CHANGES_REQUESTED** [review]
Looks great, but no need to have the " - backport 10.10" on the commit message.

**Review by poonamyadav252 — COMMENTED** [review]
It look fine!

**Review by SnehalNaik-DEV — APPROVED** [review]
Looks Good

**Review by rakeshkumar1019 — APPROVED** [review]

**Review by Nisha-QA — APPROVED** [review]
Looks good

**Pull request merged**
