### PR TITLE
ELEMENTS-224  - Adds observer to items.splices instead of items

### PR DESCRIPTION
**Pull request by pncosta**
…conditional assingment to this.size to avoid 'not defined' exceptiont

### CODE REVIEW

**Comment by nelsonsilva** [comment]
@guirenard if `this.$.list.items` is bound to `items` can't we just make `size` a computed property instead of having to keep it up to date ourselves ?

**Comment by guirenard** [comment]
@nelsonsilva yes we could but the observer on the size might then be called far too many times and slow down the rendering because of https://github.com/nuxeo/nuxeo-ui-elements/blob/70c2a5d6ddabbba7716ecf2593f69f2459e16406/nuxeo-page-provider-display-behavior.html#L215.

Else I am ok with the diff

**Comment by guirenard** [comment]
:+1:

**Comment by nelsonsilva** [comment]
👍

**Pull request merged**
