### PR TITLE
ELEMENTS-438: add shared context to slots

### PR DESCRIPTION
**Pull request by Gabez0r**

### CODE REVIEW

**Comment by adilioaraujo** [comment]
:+1:

**Comment by guirenard** [comment]
@Gabez0r not sure I got everything but what if a slot is registered after the nuxeo-app call `_computeSharedActionContext` ? (https://github.com/nuxeo/nuxeo-web-ui/pull/96/files#diff-7bdb73a7b1ca9077b50df2e9d40afcafR471)

I am thinking about dynamically loaded elements..

**Comment by Gabez0r** [comment]
When `_computeSharedActionContext` is called, `sharedModel` variable in the scope of `nuxeo-slot`is set by `window.nuxeo.slots.setSharedModel `. If a new slot is attached later on, it will run the `_updateSharedModel` method which will propagate all the properties already set on `sharedModel`.

**Comment by guirenard** [comment]
:+1:

**Pull request merged**
